import { ArcRotateCamera,Color3,Color4,DirectionalLight,Engine,HemisphericLight,Mesh,MeshBuilder,PhysicsAggregate,PhysicsShapeType,Scene,ShadowGenerator,Vector3 } from "@babylonjs/core";
import { BlockFactory,type RuntimeEntity } from "./BlockFactory"; import { ThrowController } from "./input/ThrowController"; import { loadLevel } from "./levels/loadLevel"; import type { HappyBlocksLevel,LevelObjective } from "./levels/types"; import { initPhysics } from "./physics/initPhysics"; import { createMaterialLibrary,type MaterialLibrary } from "./rendering/materials"; import { Hud } from "../ui/Hud"; import { AudioFx } from "./AudioFx";
export class HappyBlocksGame{private engine:Engine;private scene:Scene|null=null;private materials:MaterialLibrary|null=null;private level:HappyBlocksLevel|null=null;private hud=new Hud();private audio=new AudioFx();private entities:RuntimeEntity[]=[];private platform:{mesh:Mesh;aggregate:PhysicsAggregate}|null=null;private throwController:ThrowController|null=null;private shotsRemaining=0;private shotsUsed=0;private startedAt=0;private completed=false;
constructor(private canvas:HTMLCanvasElement){this.engine=new Engine(canvas,true,{preserveDrawingBuffer:false,stencil:true});window.addEventListener("resize",this.resize);window.addEventListener("keydown",this.keydown);this.hud.resetButton.addEventListener("click",()=>void this.reset())}
async start(levelUrl:string){this.level=await loadLevel(levelUrl);await this.buildScene(this.level);this.engine.runRenderLoop(()=>{if(!this.scene)return;this.update();this.scene.render()})}
private async buildScene(level:HappyBlocksLevel){this.scene?.dispose();const scene=new Scene(this.engine);this.scene=scene;scene.clearColor=new Color4(.018,.055,.068,1);scene.ambientColor=new Color3(.08,.12,.14);await initPhysics(scene,Vector3.FromArray(level.arena.gravity));const c=new ArcRotateCamera("camera",level.camera.alpha,level.camera.beta,level.camera.radius,Vector3.FromArray(level.camera.target),scene);c.lowerRadiusLimit=level.camera.minRadius??6;c.upperRadiusLimit=level.camera.maxRadius??20;c.lowerBetaLimit=.55;c.upperBetaLimit=1.45;c.wheelPrecision=32;c.attachControl(this.canvas,true);if(c.inputs.attached.pointers)c.inputs.attached.pointers.buttons=[1,2];const hemi=new HemisphericLight("sky",new Vector3(0,1,0),scene);hemi.intensity=.55;hemi.groundColor=new Color3(.08,.12,.14);const key=new DirectionalLight("key",new Vector3(-.45,-1,.35),scene);key.position=new Vector3(7,12,-8);key.intensity=2.2;const shadows=new ShadowGenerator(2048,key);shadows.usePercentageCloserFiltering=true;shadows.bias=.0008;this.materials=createMaterialLibrary(scene);this.createArena(shadows);const factory=new BlockFactory(scene,this.materials);this.entities=level.entities.map(e=>factory.create(e));this.entities.forEach(e=>shadows.addShadowCaster(e.mesh));this.shotsRemaining=level.inventory["projectile.ball"]??0;this.shotsUsed=0;this.completed=false;this.startedAt=performance.now();this.throwController=new ThrowController(scene,this.canvas,this.materials,{canThrow:()=>!this.completed&&this.shotsRemaining>0,onAim:p=>this.hud.setPower(p),onThrow:()=>{this.shotsRemaining--;this.shotsUsed++;this.hud.setShots(this.shotsRemaining);this.hud.setStatus("Impact incoming…");this.audio.play("throw")}});this.hud.setLevel(level.name);this.hud.setShots(this.shotsRemaining);this.hud.setScore(this.score());this.hud.setStatus("Drag backward, aim, release.")}
private createArena(shadows:ShadowGenerator){if(!this.scene||!this.materials)return;const mesh=MeshBuilder.CreateBox("arena",{width:11,height:.4,depth:8},this.scene);mesh.position.y=-.2;mesh.material=this.materials.platform;mesh.receiveShadows=true;const aggregate=new PhysicsAggregate(mesh,PhysicsShapeType.BOX,{mass:0,friction:.82,restitution:.04},this.scene);this.platform={mesh,aggregate};const ring=MeshBuilder.CreateTorus("arena-ring",{diameter:10.2,thickness:.04,tessellation:80},this.scene);ring.rotation.x=Math.PI/2;ring.position.y=.03;ring.material=this.materials.energy;ring.isPickable=false;shadows.addShadowCaster(ring)}
private update(){if(!this.level||this.completed)return;this.hud.setScore(this.score());if(this.level.objectives.every(o=>this.objective(o))){this.completed=true;this.hud.setStatus(`Structure solved · ${this.score().toLocaleString()} points`,"win");this.audio.play("goal");return}if(this.shotsRemaining<=0)this.hud.setStatus("No shots left — reset and try another angle.")}
private objective(o:LevelObjective){const targets=this.entities.filter(e=>e.tags.includes(o.targetTag));if(o.type==="moveBelowY")return targets.filter(e=>e.mesh.position.y<=o.y).length>=o.required;const up=Vector3.Up();return targets.filter(e=>Vector3.Dot(Vector3.TransformNormal(up,e.mesh.getWorldMatrix()).normalize(),up)<=o.maxUpDot).length>=o.required}
private score(){if(!this.level)return 0;const elapsed=Math.max(0,(performance.now()-this.startedAt)/1000),base=this.level.scoring?.base??1000,shots=(this.level.scoring?.projectilePenalty??120)*this.shotsUsed,time=(this.level.scoring?.timePenaltyPerSecond??0)*elapsed;return Math.max(0,Math.round(base-shots-time))}
async reset(){if(!this.level)return;this.throwController?.dispose();this.throwController=null;await this.buildScene(this.level)}private resize=()=>this.engine.resize();private keydown=(e:KeyboardEvent)=>{if(e.key.toLowerCase()==="r")void this.reset()};dispose(){window.removeEventListener("resize",this.resize);window.removeEventListener("keydown",this.keydown);this.throwController?.dispose();this.scene?.dispose();this.audio.dispose();this.engine.dispose()}}
