import { DynamicTexture, Scene, Texture } from "@babylonjs/core";

export type TextureKitId = "wood" | "stone" | "metal" | "rubber" | "ceramic" | "energy";
export interface TextureKit { albedo: DynamicTexture; normal: DynamicTexture; orm: DynamicTexture; emissive?: DynamicTexture; }
type MapKind = "albedo" | "normal" | "orm" | "emissive";

function seeded(seed:number):()=>number{let state=seed>>>0;return()=>{state=Math.imul(1664525,state)+1013904223;return(state>>>0)/4294967296;};}
function constrainedDevice():boolean{return window.matchMedia("(max-width: 900px)").matches||window.matchMedia("(pointer: coarse)").matches;}
function textureSize(kind:MapKind):number{const constrained=constrainedDevice();if(kind==="albedo")return constrained?1024:2048;return constrained?512:1024;}
function createTexture(scene:Scene,name:string,kind:MapKind,draw:(context:CanvasRenderingContext2D,size:number)=>void):DynamicTexture{const size=textureSize(kind);const texture=new DynamicTexture(name,{width:size,height:size},scene,true,Texture.TRILINEAR_SAMPLINGMODE);texture.wrapU=Texture.WRAP_ADDRESSMODE;texture.wrapV=Texture.WRAP_ADDRESSMODE;texture.anisotropicFilteringLevel=constrainedDevice()?4:8;texture.gammaSpace=kind==="albedo"||kind==="emissive";const context=texture.getContext() as unknown as CanvasRenderingContext2D;draw(context,size);texture.update(false);return texture;}
function fillNormal(c:CanvasRenderingContext2D,s:number):void{c.fillStyle="#8080ff";c.fillRect(0,0,s,s);}

function wood(c:CanvasRenderingContext2D,s:number,k:MapKind):void{const r=seeded(101+k.length*17);if(k==="normal"){fillNormal(c,s);c.globalAlpha=.5;for(let i=0;i<Math.max(180,s/2);i++){const y=r()*s;c.strokeStyle=r()>.5?"#687df5":"#987fff";c.lineWidth=1+r()*2.5;c.beginPath();c.moveTo(0,y);for(let x=0;x<s;x+=s/28)c.lineTo(x,y+Math.sin(x*.017+i)*(3+r()*9));c.stroke();}c.globalAlpha=1;return;}if(k==="orm"){c.fillStyle="rgb(238,158,5)";c.fillRect(0,0,s,s);c.globalAlpha=.28;for(let i=0;i<Math.max(100,s/4);i++){c.fillStyle=i%2?"rgb(210,185,5)":"rgb(245,132,5)";c.fillRect(0,r()*s,s,2+r()*4);}c.globalAlpha=1;return;}const g=c.createLinearGradient(0,0,s,0);g.addColorStop(0,"#5a3219");g.addColorStop(.34,"#bd8042");g.addColorStop(.7,"#8a5029");g.addColorStop(1,"#d89d57");c.fillStyle=g;c.fillRect(0,0,s,s);c.globalAlpha=.3;for(let i=0;i<500;i++){const y=r()*s;c.beginPath();c.moveTo(0,y);for(let x=0;x<=s;x+=s/30)c.lineTo(x,y+Math.sin(x*.018+i)*(4+r()*18));c.strokeStyle=r()>.55?"#361b0c":"#efbd74";c.lineWidth=.6+r()*2.2;c.stroke();}c.globalAlpha=1;}

function stone(c:CanvasRenderingContext2D,s:number,k:MapKind):void{const r=seeded(202+k.length*29);if(k==="normal"){fillNormal(c,s);c.globalAlpha=.42;for(let i=0;i<s*4;i++){const v=110+Math.floor(r()*36);c.fillStyle=`rgb(${v},${128+Math.floor(r()*12)},${232+Math.floor(r()*23)})`;const q=1+r()*4;c.fillRect(r()*s,r()*s,q,q);}c.globalAlpha=1;return;}if(k==="orm"){c.fillStyle="rgb(225,205,8)";c.fillRect(0,0,s,s);c.globalAlpha=.2;for(let i=0;i<Math.max(240,s);i++){c.fillStyle="rgb(190,225,8)";c.fillRect(r()*s,r()*s,2+r()*8,2+r()*8);}c.globalAlpha=1;return;}c.fillStyle="#8f9a9e";c.fillRect(0,0,s,s);for(let i=0;i<9500;i++){const shade=Math.floor(95+r()*115);c.fillStyle=`rgba(${shade},${shade+4},${shade+8},${.05+r()*.2})`;const q=.5+r()*5;c.fillRect(r()*s,r()*s,q,q);}c.globalAlpha=.3;c.strokeStyle="#3e484d";for(let crack=0;crack<38;crack++){let x=r()*s,y=r()*s;c.beginPath();c.moveTo(x,y);for(let p=0;p<7;p++){x+=(r()-.5)*s*.055;y+=r()*s*.03;c.lineTo(x,y);}c.lineWidth=.7+r()*2;c.stroke();}c.globalAlpha=1;}

function metal(c:CanvasRenderingContext2D,s:number,k:MapKind):void{const r=seeded(303+k.length*31);if(k==="normal"){fillNormal(c,s);c.globalAlpha=.38;for(let i=0;i<Math.max(500,s);i++){const x=r()*s;c.strokeStyle=r()>.5?"#747fff":"#8d81ff";c.lineWidth=.5+r();c.beginPath();c.moveTo(x,0);c.lineTo(x+(r()-.5)*8,s);c.stroke();}c.globalAlpha=1;return;}if(k==="orm"){c.fillStyle="rgb(248,78,238)";c.fillRect(0,0,s,s);c.globalAlpha=.22;for(let i=0;i<Math.max(180,s/2);i++){c.fillStyle=i%2?"rgb(245,105,240)":"rgb(245,55,235)";c.fillRect(r()*s,0,1+r()*3,s);}c.globalAlpha=1;return;}const g=c.createLinearGradient(0,0,s,0);g.addColorStop(0,"#45545b");g.addColorStop(.2,"#a5b2b7");g.addColorStop(.5,"#5b6d74");g.addColorStop(.82,"#c1c9cc");g.addColorStop(1,"#506168");c.fillStyle=g;c.fillRect(0,0,s,s);c.globalAlpha=.2;for(let i=0;i<1400;i++){const x=r()*s;c.strokeStyle=r()>.5?"#f2f8f9":"#1d292e";c.lineWidth=.35+r()*.8;c.beginPath();c.moveTo(x,0);c.lineTo(x+(r()-.5)*8,s);c.stroke();}c.globalAlpha=1;}

function rubber(c:CanvasRenderingContext2D,s:number,k:MapKind):void{const r=seeded(404+k.length*37);if(k==="normal"){fillNormal(c,s);for(let i=0;i<s*6;i++){c.fillStyle=r()>.5?"#777df3":"#8984ff";const q=.6+r()*1.8;c.fillRect(r()*s,r()*s,q,q);}return;}if(k==="orm"){c.fillStyle="rgb(224,205,0)";c.fillRect(0,0,s,s);return;}c.fillStyle="#111d21";c.fillRect(0,0,s,s);for(let i=0;i<18000;i++){const light=28+Math.floor(r()*36);c.fillStyle=`rgba(${light},${light+5},${light+8},${.05+r()*.17})`;const q=.5+r()*2.1;c.beginPath();c.arc(r()*s,r()*s,q,0,Math.PI*2);c.fill();}}
function ceramic(c:CanvasRenderingContext2D,s:number,k:MapKind):void{const r=seeded(505+k.length*41);if(k==="normal"){fillNormal(c,s);c.globalAlpha=.18;for(let i=0;i<s*3;i++){c.fillStyle=r()>.5?"#7d80fb":"#8580ff";c.fillRect(r()*s,r()*s,.5+r()*2,.5+r()*2);}c.globalAlpha=1;return;}if(k==="orm"){c.fillStyle="rgb(250,62,3)";c.fillRect(0,0,s,s);return;}const g=c.createRadialGradient(s*.32,s*.25,0,s*.5,s*.5,s*.85);g.addColorStop(0,"#fff");g.addColorStop(.45,"#edf2f2");g.addColorStop(1,"#bdc8c8");c.fillStyle=g;c.fillRect(0,0,s,s);c.globalAlpha=.18;for(let i=0;i<5000;i++){const l=135+Math.floor(r()*75);c.fillStyle=`rgb(${l},${l+3},${l+5})`;c.fillRect(r()*s,r()*s,.5+r()*2,.5+r()*2);}c.globalAlpha=1;}
function energy(c:CanvasRenderingContext2D,s:number,k:MapKind):void{const r=seeded(606+k.length*43),cell=s/24;if(k==="normal"){fillNormal(c,s);c.globalAlpha=.45;c.strokeStyle="#7380fa";c.lineWidth=Math.max(1,s/1024);for(let i=0;i<=24;i++){c.beginPath();c.moveTo(i*cell,0);c.lineTo(i*cell,s);c.stroke();c.beginPath();c.moveTo(0,i*cell);c.lineTo(s,i*cell);c.stroke();}c.globalAlpha=1;return;}if(k==="orm"){c.fillStyle="rgb(248,58,52)";c.fillRect(0,0,s,s);return;}c.fillStyle=k==="emissive"?"#001015":"#102d36";c.fillRect(0,0,s,s);c.globalCompositeOperation="screen";c.globalAlpha=k==="emissive"?.9:.55;c.strokeStyle=k==="emissive"?"#8df5ff":"#75eaff";c.lineWidth=Math.max(1,s/1024);for(let i=0;i<=24;i++){c.beginPath();c.moveTo(i*cell,0);c.lineTo(i*cell,s);c.stroke();c.beginPath();c.moveTo(0,i*cell);c.lineTo(s,i*cell);c.stroke();}for(let q=1;q<=9;q++){c.beginPath();c.arc(s/2,s/2,s*q/22,0,Math.PI*2);c.strokeStyle=q%2?"#ffe59a":"#68e7ff";c.globalAlpha=(k==="emissive"?.45:.18)+r()*.25;c.stroke();}c.globalCompositeOperation="source-over";c.globalAlpha=1;}

const drawers:Record<TextureKitId,(c:CanvasRenderingContext2D,s:number,k:MapKind)=>void>={wood,stone,metal,rubber,ceramic,energy};
function build(scene:Scene,id:TextureKitId):TextureKit{const draw=drawers[id];const kit:TextureKit={albedo:createTexture(scene,`kit-${id}-albedo`,"albedo",(c,s)=>draw(c,s,"albedo")),normal:createTexture(scene,`kit-${id}-normal`,"normal",(c,s)=>draw(c,s,"normal")),orm:createTexture(scene,`kit-${id}-orm`,"orm",(c,s)=>draw(c,s,"orm"))};if(id==="energy")kit.emissive=createTexture(scene,"kit-energy-emissive","emissive",(c,s)=>draw(c,s,"emissive"));return kit;}
export function createTextureKits(scene:Scene):Record<TextureKitId,TextureKit>{return{wood:build(scene,"wood"),stone:build(scene,"stone"),metal:build(scene,"metal"),rubber:build(scene,"rubber"),ceramic:build(scene,"ceramic"),energy:build(scene,"energy")};}
