import { Color3,LinesMesh,Mesh,MeshBuilder,PhysicsAggregate,PointerEventTypes,Scene,Vector3 } from "@babylonjs/core";
import { ASSETS } from "../AssetDefinitions"; import type { MaterialLibrary } from "../rendering/materials";
export interface ThrowEvents{canThrow:()=>boolean;onAim:(power:number)=>void;onThrow:()=>void;}
export class ThrowController{private dragStart:{x:number;y:number}|null=null;private trajectory:LinesMesh|null=null;private launchOrigin=new Vector3(0,1.55,-6.2);private target=new Vector3(0,1.65,0);private projectiles:Array<{mesh:Mesh;aggregate:PhysicsAggregate}>=[];
constructor(private scene:Scene,private canvas:HTMLCanvasElement,private materials:MaterialLibrary,private events:ThrowEvents){scene.onPointerObservable.add(info=>{const e=info.event as PointerEvent;if(info.type===PointerEventTypes.POINTERDOWN&&e.button===0)this.begin(e);if(info.type===PointerEventTypes.POINTERMOVE)this.move(e);if(info.type===PointerEventTypes.POINTERUP&&e.button===0)this.release(e);});}
private begin(e:PointerEvent){if(!this.events.canThrow())return;this.dragStart={x:e.clientX,y:e.clientY};this.events.onAim(0)}
private move(e:PointerEvent){if(!this.dragStart)return;const dx=this.dragStart.x-e.clientX,dy=this.dragStart.y-e.clientY,p=Math.min(Math.hypot(dx,dy)/Math.min(260,this.canvas.clientWidth*.34),1);this.events.onAim(p);this.drawTrajectory(this.velocity(dx,dy,p))}
private release(e:PointerEvent){if(!this.dragStart)return;const dx=this.dragStart.x-e.clientX,dy=this.dragStart.y-e.clientY,p=Math.min(Math.hypot(dx,dy)/Math.min(260,this.canvas.clientWidth*.34),1);this.dragStart=null;this.events.onAim(-1);this.disposeTrajectory();if(p<.08||!this.events.canThrow())return;this.spawn(this.velocity(dx,dy,p));this.events.onThrow()}
private velocity(dx:number,dy:number,p:number){const base=this.target.subtract(this.launchOrigin).normalize(),lateral=dx/Math.max(this.canvas.clientWidth,1),vertical=dy/Math.max(this.canvas.clientHeight,1),dir=base.add(new Vector3(lateral*3.4,vertical*2.8+.06,0)).normalize();return dir.scale(7+15*Math.pow(p,1.25))}
private spawn(v:Vector3){const d=ASSETS["projectile.ball"],mesh=MeshBuilder.CreateSphere(`projectile-${this.projectiles.length+1}`,{diameter:d.radius!*2,segments:20},this.scene);mesh.position.copyFrom(this.launchOrigin);mesh.material=this.materials.projectile;const aggregate=new PhysicsAggregate(mesh,d.physicsShape,{mass:d.mass,friction:.32,restitution:.22},this.scene);aggregate.body.setLinearVelocity(v);aggregate.body.setAngularVelocity(new Vector3(v.y*.12,-v.x*.12,v.x*.08));this.projectiles.push({mesh,aggregate})}
private drawTrajectory(v:Vector3){this.disposeTrajectory();const points:Vector3[]=[],g=new Vector3(0,-9.81,0);for(let i=0;i<22;i++){const t=i*.075;points.push(this.launchOrigin.add(v.scale(t)).add(g.scale(.5*t*t)))}this.trajectory=MeshBuilder.CreateLines("trajectory",{points},this.scene);this.trajectory.color=new Color3(.35,.92,1);this.trajectory.alpha=.72;this.trajectory.isPickable=false}
private disposeTrajectory(){this.trajectory?.dispose();this.trajectory=null}reset(){this.dragStart=null;this.disposeTrajectory();for(const p of this.projectiles){p.aggregate.dispose();p.mesh.dispose()}this.projectiles.length=0}dispose(){this.reset()}}
